### ISSUE TITLE
Nested strings in attributes

### ISSUE THREAD

**Issue by youdz** [arnauddri/npm-html2js#2]
To fix the [previous issue](https://github.com/arnauddri/npm-html2js/issues/1), you replace single quotes `'` by double quotes `"`. But this breaks typical Angular HTML like this one: 

``` html
<span ng-class="{'my-error': errors['foo']}">Foo</span>
```

This is translated to: 

``` html
<span ng-class="{"my-error": errors["foo"]}">Foo</span>
```

which is clearly not valid HTML.

I believe single quotes should simply be escaped instead of replaced by double quotes, and the `\` should also be escape into `\\`.

**Comment by youdz** [comment]
I actually just fixed it locally, and I don't think it's necessary to create a pull request just for this. Here is the fix: 

line 57 of index.js, instead of: 

``` javascript
html = html.replace(/'/g, '"');
```

use: 

``` javascript
html = html.replace(/\\/g, '\\\\');
html = html.replace(/'/g, '\\\'');
```

**Comment by arnauddri** [comment]
thanks! I just fixed it!
